# Generated by Django 5.1 on 2025-01-21 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navire',
            fields=[
                ('id', models.TextField(max_length=62, primary_key=True, serialize=False, unique=True)),
                ('entreprise', models.TextField(max_length=62)),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('temps', models.TimeField()),
                ('navire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishin.navire')),
            ],
        ),
    ]
