# Generated by Django 5.1 on 2025-01-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navire',
            name='image',
            field=models.ImageField(default=11, upload_to='navire/'),
            preserve_default=False,
        ),
    ]
