# Generated by Django 5.1.6 on 2025-02-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishin', '0004_alter_historique_navire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navire',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='navire/'),
        ),
    ]
